import { LoanAgainstPropertyLender } from "./type";

export const FALLBACK_LAP_LENDERS: LoanAgainstPropertyLender[] = [
  {
    id: "sbi-loan-against-property",
    name: "SBI Loan Against Property",
    logo: "/partners-logos/sbi-logo.webp",
    tagline: "India's premier sovereign mortgage financing with transparent MCLR/EBLR benchmark rates",
    bankType: "psu",
    interestRate: {
      min: 10.10,
      max: 11.65,
      text: "10.10% - 11.65% p.a.",
    },
    startingEmiPerLakh15Yr: 1081,
    startingEmiPerLakh20Yr: 972,
    maxAmount: "Up to ₹7.5 Crore (Min ₹10 Lakhs)",
    maxAmountNum: 75000000,
    maxTenure: "Up to 15 Years (180 months)",
    tenureYears: 15,
    processingFee: "1.00% of loan amount + GST (Capped at ₹50,000 + GST)",
    processingFeePercent: 1.0,
    processingFeeCap: "Max ₹50,000 + GST",
    maxLtv: "Up to 65% for loans ≤ ₹1 Cr; 60% for loans up to ₹7.5 Cr",
    maxLtvPercent: 65,
    propertyTypesAccepted: [
      "Self-occupied Residential Flat/House",
      "Commercial Office/Shop",
      "Vacant Residential Property",
    ],
    overdraftAvailable: false,
    overdraftScheme: null,
    foreclosureCharges: "Nil / 0% penalty on floating rate loans for individual borrowers (RBI compliant)",
    minCreditScore: 720,
    minIncome: "Salaried: ₹25,000/mo | Non-salaried: ₹3,00,000/yr",
    features: [
      "Sovereign security with transparent interest rates linked to benchmark lending rates",
      "Processing charges legally capped at ₹50,000, saving substantial amounts on high-ticket loans",
      "Available for resident Indians and NRIs owning self-occupied or commercial properties",
      "No prepayment or foreclosure penalty on floating rate loans for individual borrowers",
    ],
    pros: [
      "Processing fee capped at ₹50k",
      "Sovereign lender transparency",
      "Zero floating rate prepayment penalty",
    ],
    recommendedFor: "Salaried professionals, government employees, and self-employed seeking reliable sovereign financing",
    rating: 4.8,
    reviewCount: "34.6k",
    badge: "Lowest Processing Fee Cap",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "psu", "low-rate"],
  },
  {
    id: "hdfc-loan-against-property",
    name: "HDFC Bank Loan Against Property",
    logo: "/partners-logos/hdfc-logo.webp",
    tagline: "High-ticket mortgage loans with drop-line overdraft options and digital approvals",
    bankType: "private",
    interestRate: {
      min: 9.30,
      max: 10.75,
      text: "9.30% - 10.75% p.a.",
    },
    startingEmiPerLakh15Yr: 1033,
    startingEmiPerLakh20Yr: 919,
    maxAmount: "Up to ₹10 Crore (Custom sanctions higher)",
    maxAmountNum: 100000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "Up to 1.00% of loan amount or ₹10,000 (whichever is higher) + GST",
    processingFeePercent: 1.0,
    processingFeeCap: null,
    maxLtv: "Up to 65% on residential; up to 55% on commercial properties",
    maxLtvPercent: 65,
    propertyTypesAccepted: [
      "Residential Apartments",
      "Commercial Offices",
      "Independent Villas",
    ],
    overdraftAvailable: true,
    overdraftScheme: "HDFC Property Overdraft facility available",
    foreclosureCharges: "Nil for individual borrowers with floating rates",
    minCreditScore: 720,
    minIncome: "Salaried: ₹40,000/mo | Self-employed: ₹4,00,000/yr",
    features: [
      "Flexible repayment via term loan or dropline overdraft",
      "Digital in-principle approval with doorstep legal support",
      "Accepted for business expansion, debt consolidation, and working capital",
    ],
    pros: [
      "Dropline overdraft flexibility",
      "Fast 5-day disbursal timeline",
      "High sanction limit up to ₹10 Cr",
    ],
    recommendedFor: "Business owners, professionals, and corporate salaried individuals needing fast capital",
    rating: 4.9,
    reviewCount: "42.1k",
    badge: "Best Overdraft Scheme",
    badgeColor: "bg-primary/10 text-primary border-primary/20",
    category: ["all", "private", "overdraft", "low-rate"],
  },
  {
    id: "icici-loan-against-property",
    name: "ICICI Bank Loan Against Property",
    logo: "/partners-logos/icici-logo.webp",
    tagline: "Competitive mortgage rates with multi-crore ticket sizes and pre-approved offers",
    bankType: "private",
    interestRate: {
      min: 9.45,
      max: 10.85,
      text: "9.45% - 10.85% p.a.",
    },
    startingEmiPerLakh15Yr: 1042,
    startingEmiPerLakh20Yr: 929,
    maxAmount: "Up to ₹15 Crore",
    maxAmountNum: 150000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "1.00% + GST",
    processingFeePercent: 1.0,
    processingFeeCap: null,
    maxLtv: "Up to 70% for residential; up to 60% for commercial",
    maxLtvPercent: 70,
    propertyTypesAccepted: [
      "Residential Flat/Bungalow",
      "Commercial Complex",
      "Rented Commercial Property",
    ],
    overdraftAvailable: true,
    overdraftScheme: "ICICI Money Saver LAP facility available",
    foreclosureCharges: "Nil on floating rates for individuals",
    minCreditScore: 700,
    minIncome: "Salaried: ₹35,000/mo | Self-employed: ₹3,50,000/yr",
    features: [
      "High LTV up to 70% of property market value",
      "ICICI Money Saver overdraft linked current account",
      "Minimal documentation for existing ICICI customers",
    ],
    pros: [
      "High 70% LTV on residential",
      "Paperless e-approval",
      "Multi-city property funding",
    ],
    recommendedFor: "Salaried employees and retail business owners seeking high valuation funding",
    rating: 4.8,
    reviewCount: "38.5k",
    badge: "High 70% LTV",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "private", "overdraft", "high-ltv"],
  },
  {
    id: "axis-bank-loan-against-property",
    name: "Axis Bank Loan Against Property",
    logo: "/partners-logos/axis-logo.webp",
    tagline: "Customized mortgage solutions for residential and commercial property owners",
    bankType: "private",
    interestRate: {
      min: 9.25,
      max: 10.95,
      text: "9.25% - 10.95% p.a.",
    },
    startingEmiPerLakh15Yr: 1030,
    startingEmiPerLakh20Yr: 916,
    maxAmount: "Up to ₹25 Crore (Min ₹10 Lakhs)",
    maxAmountNum: 250000000,
    maxTenure: "Up to 20 Years",
    tenureYears: 20,
    processingFee: "1.00% of loan amount (Min ₹10,000) + GST",
    processingFeePercent: 1.0,
    processingFeeCap: null,
    maxLtv: "Up to 70% on residential; up to 60% on commercial properties",
    maxLtvPercent: 70,
    propertyTypesAccepted: [
      "Residential Property",
      "Commercial Property",
      "Plot + Construction",
    ],
    overdraftAvailable: true,
    overdraftScheme: "Axis Smart LAP Overdraft available",
    foreclosureCharges: "Nil for individual borrowers on floating rate loans",
    minCreditScore: 700,
    minIncome: "Salaried: ₹30,000/mo | Non-salaried: ₹3,00,000/yr",
    features: [
      "Long 20-year tenure reducing monthly EMI commitments",
      "Funding up to ₹25 Crore for major business projects",
      "Balance transfer with additional high-value top-up",
    ],
    pros: [
      "Longest 20-year tenure",
      "Multi-crore funding up to ₹25 Cr",
      "Overdraft facility available",
    ],
    recommendedFor: "Large MSME enterprises and commercial landlords looking for high ticket size",
    rating: 4.7,
    reviewCount: "29.4k",
    badge: "Funding up to ₹25 Cr",
    badgeColor: "bg-amber-50 text-amber-800 border-amber-200",
    category: ["all", "private", "overdraft", "high-ltv", "low-rate"],
  },
  {
    id: "bank-of-baroda-mortgage-loan",
    name: "Bank of Baroda Mortgage Loan",
    logo: "/partners-logos/bob-logo.webp",
    tagline: "Public sector reliability with competitive Baroda Repo Linked Lending Rate (BRLLR)",
    bankType: "psu",
    interestRate: {
      min: 9.40,
      max: 10.70,
      text: "9.40% - 10.70% p.a.",
    },
    startingEmiPerLakh15Yr: 1039,
    startingEmiPerLakh20Yr: 925,
    maxAmount: "Up to ₹10 Crore (Metro locations)",
    maxAmountNum: 100000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "0.50% to 1.00% + GST (Capped at ₹1 Lakh)",
    processingFeePercent: 0.75,
    processingFeeCap: "Max ₹1,00,000 + GST",
    maxLtv: "Up to 60% of realisable property value",
    maxLtvPercent: 60,
    propertyTypesAccepted: [
      "Residential House/Flat",
      "Commercial Building",
    ],
    overdraftAvailable: true,
    overdraftScheme: "Baroda Mortgage Overdraft Scheme",
    foreclosureCharges: "Nil on floating rate loans for individuals",
    minCreditScore: 701,
    minIncome: "Salaried: ₹25,000/mo | Non-salaried: ₹2,50,000/yr",
    features: [
      "Competitive BRLLR linked interest rate structure",
      "Lower processing fee slabs for sovereign borrowers",
      "Available across 8,000+ pan-India branches",
    ],
    pros: [
      "PSU trust & transparency",
      "Low processing fees",
      "Overdraft available",
    ],
    recommendedFor: "Salaried employees and traders seeking PSU bank transparency and stable rates",
    rating: 4.6,
    reviewCount: "22.8k",
    badge: "PSU BRLLR Linked",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "psu", "overdraft", "low-rate"],
  },
  {
    id: "kotak-loan-against-property",
    name: "Kotak Mahindra Bank Loan Against Property",
    logo: "/partners-logos/kotak-logo.webp",
    tagline: "Personalized relationship banking with rapid technical valuation and OD facility",
    bankType: "private",
    interestRate: {
      min: 9.50,
      max: 11.00,
      text: "9.50% - 11.00% p.a.",
    },
    startingEmiPerLakh15Yr: 1044,
    startingEmiPerLakh20Yr: 932,
    maxAmount: "Up to ₹10 Crore",
    maxAmountNum: 100000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "Up to 1.00% + GST",
    processingFeePercent: 1.0,
    processingFeeCap: null,
    maxLtv: "Up to 60% on residential; up to 55% on commercial properties",
    maxLtvPercent: 60,
    propertyTypesAccepted: [
      "Self-occupied Residential Property",
      "Commercial Office Space",
    ],
    overdraftAvailable: true,
    overdraftScheme: "Kotak Dropline Overdraft available",
    foreclosureCharges: "Nil for individuals on floating rate",
    minCreditScore: 720,
    minIncome: "Salaried: ₹40,000/mo | Self-employed: ₹4,00,000/yr",
    features: [
      "Dedicated mortgage relationship manager",
      "Fast technical and legal evaluation turnaround",
      "Transparent fee structure with zero hidden levies",
    ],
    pros: [
      "High relationship manager support",
      "Quick sanction timeline",
      "Dropline OD available",
    ],
    recommendedFor: "Professionals (doctors, CAs, lawyers) and MSME business proprietors",
    rating: 4.7,
    reviewCount: "25.3k",
    badge: "Quick Turnaround",
    badgeColor: "bg-primary/10 text-primary border-primary/20",
    category: ["all", "private", "overdraft"],
  },
  {
    id: "bajaj-finserv-loan-against-property",
    name: "Bajaj Finserv Loan Against Property",
    logo: "/partners-logos/bajaj-logo.webp",
    tagline: "India's highest LTV mortgage funding with unique Flexi Hybrid Term Loan limits",
    bankType: "nbfc",
    interestRate: {
      min: 9.75,
      max: 12.00,
      text: "9.75% - 12.00% p.a.",
    },
    startingEmiPerLakh15Yr: 1059,
    startingEmiPerLakh20Yr: 949,
    maxAmount: "Up to ₹10.5 Crore",
    maxAmountNum: 105000000,
    maxTenure: "Up to 18 Years",
    tenureYears: 18,
    processingFee: "Up to 1.50% + GST",
    processingFeePercent: 1.5,
    processingFeeCap: null,
    maxLtv: "Up to 75% for residential properties",
    maxLtvPercent: 75,
    propertyTypesAccepted: [
      "Residential Flats & Houses",
      "Commercial Offices & Shops",
      "Industrial Properties",
    ],
    overdraftAvailable: true,
    overdraftScheme: "Bajaj Flexi Hybrid Loan (Pay interest only on drawn amount)",
    foreclosureCharges: "Nil for individual borrowers on floating rate",
    minCreditScore: 685,
    minIncome: "Salaried: ₹30,000/mo | Self-employed: ₹3,00,000/yr",
    features: [
      "Industry-leading 75% LTV on residential properties",
      "Flexi Hybrid loan allows paying interest-only EMIs during the initial tenor",
      "Minimal documentation with 72-hour sanction approval",
    ],
    pros: [
      "Highest 75% LTV ratio",
      "Flexi interest-only EMI option",
      "CIBIL score from 685 accepted",
    ],
    recommendedFor: "Borrowers needing maximum valuation funding and flexible initial cash-flow relief",
    rating: 4.8,
    reviewCount: "47.2k",
    badge: "Highest 75% LTV",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "nbfc", "overdraft", "high-ltv"],
  },
  {
    id: "tata-capital-loan-against-property",
    name: "Tata Capital Loan Against Property",
    logo: "/partners-logos/tata-logo.webp",
    tagline: "Backed by Tata Trust with competitive interest rates and tailored business limits",
    bankType: "nbfc",
    interestRate: {
      min: 9.60,
      max: 11.50,
      text: "9.60% - 11.50% p.a.",
    },
    startingEmiPerLakh15Yr: 1050,
    startingEmiPerLakh20Yr: 938,
    maxAmount: "Up to ₹7.5 Crore",
    maxAmountNum: 75000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "Up to 1.25% + GST",
    processingFeePercent: 1.25,
    processingFeeCap: null,
    maxLtv: "Up to 70% on residential; up to 60% on commercial properties",
    maxLtvPercent: 70,
    propertyTypesAccepted: [
      "Residential Homes",
      "Commercial Real Estate",
      "Industrial Sheds",
    ],
    overdraftAvailable: false,
    overdraftScheme: null,
    foreclosureCharges: "Nil for individual borrowers on floating rate",
    minCreditScore: 700,
    minIncome: "Salaried: ₹30,000/mo | Self-employed: ₹3,00,000/yr",
    features: [
      "Trusted Tata group governance and transparent underwriting",
      "Quick doorstep document pickup and verification",
      "Structured customized repayment schedules for businesses",
    ],
    pros: [
      "Tata Trust & transparency",
      "High 70% LTV",
      "Accepts industrial sheds",
    ],
    recommendedFor: "Manufacturers, contractors, and traders requiring structured mortgage credit",
    rating: 4.7,
    reviewCount: "21.6k",
    badge: "Tata Brand Trust",
    badgeColor: "bg-primary/10 text-primary border-primary/20",
    category: ["all", "nbfc", "high-ltv"],
  },
  {
    id: "pnb-my-property-loan",
    name: "PNB My Property Loan",
    logo: "/partners-logos/punjab-logo.webp",
    tagline: "Sovereign mortgage financing with affordable rates for MSMEs and salaried earners",
    bankType: "psu",
    interestRate: {
      min: 10.25,
      max: 11.75,
      text: "10.25% - 11.75% p.a.",
    },
    startingEmiPerLakh15Yr: 1090,
    startingEmiPerLakh20Yr: 982,
    maxAmount: "Up to ₹5 Crore",
    maxAmountNum: 50000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "1.00% + GST (Capped at ₹50,000 + GST)",
    processingFeePercent: 1.0,
    processingFeeCap: "Max ₹50,000 + GST",
    maxLtv: "Up to 65% for residential; up to 55% for commercial",
    maxLtvPercent: 65,
    propertyTypesAccepted: [
      "Residential Flat/Plot",
      "Commercial Shop/Office",
    ],
    overdraftAvailable: false,
    overdraftScheme: null,
    foreclosureCharges: "Nil for individual floating rate loans",
    minCreditScore: 700,
    minIncome: "Salaried: ₹25,000/mo | Non-salaried: ₹2,50,000/yr",
    features: [
      "Capped processing fee at ₹50,000",
      "Transparent RLLR interest pricing",
      "Expansive branch coverage across Tier 1, 2, and 3 cities",
    ],
    pros: [
      "Fee capped at ₹50k",
      "PSU transparency",
      "Deep Tier-2/3 reach",
    ],
    recommendedFor: "Borrowers in semi-urban and Tier 2/3 locations looking for a trusted PSU bank",
    rating: 4.5,
    reviewCount: "19.3k",
    badge: "PSU Fee Cap ₹50k",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "psu"],
  },
  {
    id: "idfc-first-bank-loan-against-property",
    name: "IDFC FIRST Bank Loan Against Property",
    logo: "/partners-logos/idfc-logo.webp",
    tagline: "Modern customer-first banking with high 80% LTV norms and paperless processes",
    bankType: "private",
    interestRate: {
      min: 9.50,
      max: 11.25,
      text: "9.50% - 11.25% p.a.",
    },
    startingEmiPerLakh15Yr: 1044,
    startingEmiPerLakh20Yr: 932,
    maxAmount: "Up to ₹10 Crore",
    maxAmountNum: 100000000,
    maxTenure: "Up to 15 Years",
    tenureYears: 15,
    processingFee: "1.00% + GST",
    processingFeePercent: 1.0,
    processingFeeCap: null,
    maxLtv: "Up to 80% on select residential properties",
    maxLtvPercent: 80,
    propertyTypesAccepted: [
      "Residential Properties",
      "Commercial Offices",
      "Mixed-use Properties",
    ],
    overdraftAvailable: true,
    overdraftScheme: "IDFC FIRST LAP Overdraft available",
    foreclosureCharges: "Nil on floating rate loans for individuals",
    minCreditScore: 700,
    minIncome: "Salaried: ₹35,000/mo | Self-employed: ₹3,50,000/yr",
    features: [
      "Market-leading LTV up to 80% for prime residential properties",
      "Seamless netbanking-integrated overdraft account",
      "Speedy approval with digital income assessment",
    ],
    pros: [
      "Highest 80% LTV potential",
      "Customer-first digital service",
      "Overdraft facility available",
    ],
    recommendedFor: "New-age entrepreneurs and professionals looking for modern digital banking",
    rating: 4.8,
    reviewCount: "31.7k",
    badge: "Highest 80% LTV",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    category: ["all", "private", "overdraft", "high-ltv"],
  },
];
